version: '3.8'

services:
  doduo-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=doduo
      - POSTGRES_PASSWORD=doduo
    ports:
      - "5432:5432"
    volumes:
      - doduo-postgres:/var/lib/postgresql/data

volumes:
  doduo-postgres: